# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fddfb376e65dba2a15fd93ecf55db692d6012c7d10a0d91cbe7335b04d68f2b7564432ac8a5af33c2b989b8c6121a16d6571c9264d88fbb7708b2cc45408093d

test:
  secret_key_base: 2b039eaa13a264c5b29f8bb16583876e762fd189df5cb0e87cc62fcbfdb72ac06cd09e716871f8a6345839186092aab4de0dd49cb74607371b56a748139a8b78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
